# Generated by Django 3.2.1 on 2021-06-08 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwishlist',
            name='Product_wishlist_Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 12, 52, 34, 866765)),
        ),
    ]
