# Generated by Django 3.2.1 on 2021-05-09 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Types', models.CharField(choices=[('home', 'home'), ('office', 'office')], default='home', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=40)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country')),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PincodeArea', models.CharField(max_length=40)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.area')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=40)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.state')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.city'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=256)),
                ('LastName', models.CharField(max_length=256)),
                ('Contact', models.IntegerField()),
                ('StreetAddress', models.CharField(max_length=256)),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.addresstype')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pincode')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
