# Generated by Django 3.2.1 on 2021-05-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210511_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default_address_status',
        ),
    ]
