# Generated by Django 3.2.1 on 2021-05-13 18:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_Product', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Img_1', models.ImageField(upload_to=home.models.img_path)),
                ('Product_Img_2', models.ImageField(upload_to=home.models.img_path)),
                ('Product_Img_3', models.ImageField(upload_to=home.models.img_path)),
                ('Product_Img_4', models.ImageField(upload_to=home.models.img_path)),
                ('Product_Img_5', models.ImageField(upload_to=home.models.img_path)),
                ('Product_Upload_Date', models.DateTimeField(default=datetime.datetime(2021, 5, 14, 0, 21, 52, 625432))),
                ('Product_Title', models.CharField(max_length=256)),
                ('Product_Price', models.FloatField()),
                ('Product_Percentage_Off', models.FloatField()),
                ('Product_Cutoff_Price', models.FloatField()),
                ('Product_Disc', models.CharField(max_length=50000)),
                ('Product_Stock', models.IntegerField(default=1)),
                ('Product_Weight', models.FloatField()),
                ('Product_Warrenty', models.FloatField(default=1.0)),
                ('Product_Garenty', models.FloatField(default=1.0)),
                ('ProductShipping', models.CharField(choices=[('charge', 'charge'), ('free', 'free')], default='charge', max_length=256)),
                ('mainproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mainproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_Category', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Tags', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Category', models.CharField(max_length=256)),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productmaincategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_DateTime', models.DateTimeField(default=datetime.datetime(2021, 5, 14, 0, 21, 52, 629428))),
                ('Review_Star_Select', models.CharField(choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default='1', max_length=10)),
                ('Review_Discription', models.CharField(max_length=3500)),
                ('Review_Name', models.CharField(max_length=256)),
                ('Review_Email', models.CharField(max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Policy', models.CharField(max_length=1150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMainInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Information', models.CharField(max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=256)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product_SubInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Sub_Information', models.CharField(max_length=256)),
                ('product_main_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productmaininformation')),
            ],
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='productcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productcategory'),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=256)),
                ('product_subInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_subinformation')),
            ],
        ),
    ]
