# Generated by Django 3.2.1 on 2021-05-25 17:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20210515_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='maincategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productmaincategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductShipping',
            field=models.CharField(choices=[('charge', 'charge'), ('free', 'free')], default='charge', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Cutoff_Price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Disc',
            field=models.CharField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Garenty',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Img_1',
            field=models.ImageField(null=True, upload_to=home.models.img_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Img_2',
            field=models.ImageField(null=True, upload_to=home.models.img_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Img_3',
            field=models.ImageField(null=True, upload_to=home.models.img_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Img_4',
            field=models.ImageField(null=True, upload_to=home.models.img_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Img_5',
            field=models.ImageField(null=True, upload_to=home.models.img_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Percentage_Off',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Stock',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 22, 42, 41, 634838), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Warrenty',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainproduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.mainproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='Review_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 22, 42, 41, 650467)),
        ),
    ]
