# Generated by Django 3.2.1 on 2021-06-03 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210525_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_subinformation',
            name='product_main_information',
        ),
        migrations.AddField(
            model_name='product_subinformation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 17, 58, 36, 803117), null=True),
        ),
        migrations.AlterField(
            model_name='product_subinformation',
            name='Product_Sub_Information',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='Review_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 17, 58, 36, 806114)),
        ),
        migrations.DeleteModel(
            name='ProductMainInformation',
        ),
    ]
