# Generated by Django 3.2.1 on 2021-06-06 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210603_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='Review_Email',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='Review_Name',
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 1, 12, 52, 917998), null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='Review_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 1, 12, 52, 923994)),
        ),
    ]
