# Generated by Django 3.2.1 on 2021-06-10 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210607_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 9, 25, 11, 949929), null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='Review_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 9, 25, 11, 949929)),
        ),
    ]
